"""Pydantic models and domain entities."""

from app.models.circuit import (
    Annotation,
    CircuitComponent,
    CircuitState,
    ComponentType,
    Pin,
    PinType,
    Position,
    Rotation,
    StrokeData,
    StrokeWidth,
    TextData,
    Wire,
)
from app.models.course import (
    BlueprintComponent,
    BlueprintWire,
    BuildStep,
    CircuitBlueprint,
    ComponentSpec,
    CoursePlan,
    CourseEnrollment,
    Difficulty,
    GeneratePlanRequest,
    GenerationState,
    KeyTerm,
    LevelContent,
    LevelOutline,
    LevelProgress,
    LevelStatus,
    PracticalSection,
    RequiredComponent,
    RequiredConnection,
    TheorySection,
    TopicSuggestion,
    ValidationCriteria,
    ValidationResult,
)
from app.models.session import (
    EditRequest,
    EditRequestStatus,
    Participant,
    Role,
    Session,
)

__all__ = [
    # Circuit models
    "Annotation",
    "CircuitComponent",
    "CircuitState",
    "ComponentType",
    "Pin",
    "PinType",
    "Position",
    "Rotation",
    "StrokeData",
    "StrokeWidth",
    "TextData",
    "Wire",
    # Course models
    "BlueprintComponent",
    "BlueprintWire",
    "BuildStep",
    "CircuitBlueprint",
    "ComponentSpec",
    "CoursePlan",
    "CourseEnrollment",
    "Difficulty",
    "GeneratePlanRequest",
    "GenerationState",
    "KeyTerm",
    "LevelContent",
    "LevelOutline",
    "LevelProgress",
    "LevelStatus",
    "PracticalSection",
    "RequiredComponent",
    "RequiredConnection",
    "TheorySection",
    "TopicSuggestion",
    "ValidationCriteria",
    "ValidationResult",
    # Session models
    "EditRequest",
    "EditRequestStatus",
    "Participant",
    "Role",
    "Session",
]
