"""Course-plan models: the high-level outline an LLM produces for a topic.

Why this module exists separately
---------------------------------
A *course plan* is the table of contents: a title, difficulty, and an ordered
list of level outlines. The detailed per-level content lives in
:mod:`.content`; this module is just the skeleton.

Shape
-----
``CoursePlan`` has 8-20 ``LevelOutline`` entries (the generator is prompted to
stay in that range). Each outline is a one-line "what you'll build" summary;
the real lesson is filled in later, on demand, per level.
"""

from datetime import datetime

from pydantic import BaseModel, Field

from .enums import Difficulty


class LevelOutline(BaseModel):
    """Brief outline of a level (part of course plan)."""

    level_number: int = Field(alias="levelNumber", ge=1)
    title: str = Field(min_length=1, max_length=100)
    description: str = Field(min_length=1, max_length=500)

    model_config = {"populate_by_name": True}


class CoursePlan(BaseModel):
    """Complete course plan generated by LLM."""

    id: str | None = None
    topic: str = Field(min_length=1, max_length=200)
    title: str = Field(min_length=1, max_length=200)
    description: str = Field(min_length=1, max_length=2000)
    difficulty: Difficulty
    estimated_hours: float = Field(alias="estimatedHours", ge=1, le=100)
    levels: list[LevelOutline] = Field(min_length=8, max_length=20)
    created_at: datetime = Field(default_factory=datetime.utcnow, alias="createdAt")
    creator_participant_id: str | None = Field(
        default=None, alias="creatorParticipantId"
    )

    model_config = {"populate_by_name": True}
